// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCvHBtOSPwDA_SzLA1v-0QVlr_gdn9eEwY',
    appId: '1:3042186044:web:37acbe11cd224f319d8439',
    messagingSenderId: '3042186044',
    projectId: 'ecommerce-28f9d',
    authDomain: 'ecommerce-28f9d.firebaseapp.com',
    storageBucket: 'ecommerce-28f9d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxOOBUsu9nn7FfY_JB-MAMr7qi4YtYK7U',
    appId: '1:3042186044:android:5e9d7c6f9f973cec9d8439',
    messagingSenderId: '3042186044',
    projectId: 'ecommerce-28f9d',
    storageBucket: 'ecommerce-28f9d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC9uDcSKXdtw8RJqHFJRLz0uaYBldQHphQ',
    appId: '1:3042186044:ios:180029ca4edb21c09d8439',
    messagingSenderId: '3042186044',
    projectId: 'ecommerce-28f9d',
    storageBucket: 'ecommerce-28f9d.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC9uDcSKXdtw8RJqHFJRLz0uaYBldQHphQ',
    appId: '1:3042186044:ios:180029ca4edb21c09d8439',
    messagingSenderId: '3042186044',
    projectId: 'ecommerce-28f9d',
    storageBucket: 'ecommerce-28f9d.appspot.com',
    iosBundleId: 'com.example.eCommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCvHBtOSPwDA_SzLA1v-0QVlr_gdn9eEwY',
    appId: '1:3042186044:web:297f4b35758e3d1d9d8439',
    messagingSenderId: '3042186044',
    projectId: 'ecommerce-28f9d',
    authDomain: 'ecommerce-28f9d.firebaseapp.com',
    storageBucket: 'ecommerce-28f9d.appspot.com',
  );

}